########################################################################################################################
# GLOBAL
########################################################################################################################

global:

  cluster:

    istio:
      enabled: false

  metrics:
    prometheus:
      enabled: false
      retention: 1w
    scrape:
      interval: 10s
      timeout: 10s
    servicemonitor:
      enabled: false

########################################################################################################################
# LOCAL
########################################################################################################################

nameOverride: edusharing

image:
  pullSecrets: []
#  - name: registry
#    server: registry.docker.edu-sharing.com
#    username: someone
#    password: secret

########################################################################################################################
# DEPENDENCY
########################################################################################################################

edusharing_rediscluster:

  enabled: true

  nameOverride: &redisclusterNameOverride edusharing-rediscluster

  service:
    port:
      api: &redisclusterServicePortApi 6379

########################################################################################################################

edusharing_repository:

  enabled: true

  edusharing_repository_rediscluster:

    enabled: false

  edusharing_repository_postgresql:

    enabled: true

    nameOverride: &repositoryPostgresqlNameOverride edusharing-repository-postgresql

    config:
      patroni:
        enabled: false
        name: *repositoryPostgresqlNameOverride

  edusharing_repository_service:

    nameOverride: &repositoryNameOverride edusharing-repository-service

    service:
      port:
        api:
          internal: &repositoryServicePostApiInternal 8080

    config:

      admin:
        password: &repositoryConfigAdminPassword admin

      cache:
        host: *redisclusterNameOverride
        port: *redisclusterServicePortApi

########################################################################################################################

edusharing_services_rendering:

  enabled: true

  edusharing_services_rendering_rediscluster:

    enabled: false

  edusharing_services_rendering_postgresql:

    enabled: true

    nameOverride: &renderingPostgresqlNameOverride edusharing-services-rendering-postgresql

    config:
      patroni:
        enabled: false
        name: *renderingPostgresqlNameOverride

  edusharing_services_rendering_service:

    config:

      cache:
        host: *redisclusterNameOverride
        port: *redisclusterServicePortApi

      repository:
        host: *repositoryNameOverride
        port: *repositoryServicePostApiInternal
        password: *repositoryConfigAdminPassword

########################################################################################################################
