image: maven:3.6.3-jdk-8

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MAVEN_CLI_OPTS: "-s .mvn/settings.xml --batch-mode --errors --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/

before_script:
  - if [ -n "$CI_COMMIT_TAG" ]; then
      export VERSIONING_GIT_TAG=$CI_COMMIT_TAG;
    else
      export VERSIONING_GIT_BRANCH=$CI_COMMIT_REF_NAME;
    fi

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS deploy
