variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MAVEN_CLI: "-Ddocker.registry=$DOCKER_REGISTRY -Dhelm.deploy.url=$HELM_REGISTRY -Dhelm.deploy.type=$HELM_TYPE -Dmaven.deploy.releases=$MAVEN_DEPLOY_RELEASES -Dmaven.deploy.snapshots=$MAVEN_DEPLOY_SNAPSHOTS --batch-mode --errors --fail-fast --show-version"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

default:
  image: maven:3.8.4-jdk-8

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - mvn $MAVEN_CLI -s .mvn/settings.xml deploy
