{{- range .Values.image.pullSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  labels: {{ include "edusharing.labels" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "edusharing.dockerconfigjson" . }}
{{- end }}
