apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_services_rendering.name" . }}
  labels: {{ include "edusharing_services_rendering.labels.app" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_services_rendering.labels.app" . | nindent 6 }}
  serviceName: {{ include "edusharing_services_rendering.name" . }}-headless
  template:
    metadata:
      labels: {{ include "edusharing_services_rendering.labels.app" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9117"
        prometheus.io/scrape: {{ .Values.sidecar.metrics.enabled | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if (default .Values.global.cluster.storage.share.permission .Values.persistence.share.permission) }}
      - name: {{ include "edusharing_services_rendering.name" . }}-init-permission
        image: {{ include "edusharing_services_rendering.image" . }}{{ .Values.image.prefix }}-deploy-docker-build-minideb:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /var/cache/esrender/config
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /var/cache/esrender/data
        volumeMounts:
          - name: share-config
            mountPath: /var/cache/esrender/config
          - name: share-data
            mountPath: /var/cache/esrender/data
          {{- with .Values.config.override.logging.application }}
          - name: file
            mountPath: /var/www/html/esrender/conf/de.metaventis.esrender.log4php.xml
            subPath: logging-application
          {{- end }}
        {{- with .Values.init.permission.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.permission.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_services_rendering.name" . }}
        image: {{ include "edusharing_services_rendering.image" . }}{{ .Values.image.prefix }}-deploy-docker-services-rendering-build-service:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- $patroni := merge .Values.config.database.patroni .Values.global.patroni }}
        {{- if $patroni.enabled }}
        env:
        - name: SERVICES_RENDERING_DATABASE_PASS
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.database.username }}.{{ $patroni.name }}.{{ $patroni.secrets }}
              key: password
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_services_rendering.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_services_rendering.name" . }}-env
        ports:
        - name: api-internal
          containerPort: 8080
        - name: api-external
          containerPort: 8081
        volumeMounts:
        - name: share-config
          mountPath: /var/cache/esrender/config
        - name: share-data
          mountPath: /var/cache/esrender/data
        {{- with .Values.startupProbe }}
        startupProbe:
          httpGet:
            path: /esrender/application/esmain/version.php
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /esrender/application/esmain/version.php
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.sidecar.metrics.enabled }}
      - name: {{ include "edusharing_services_rendering.name" . }}-metrics
        image: {{ include "edusharing_services_rendering.image" . }}{{ .Values.image.prefix }}-deploy-docker-build-apache_exporter:{{ .Values.image.tag }}
        args:
        - --scrape_uri=http://127.0.0.1:8082/server-status/?auto
        - --telemetry.address=:9117
        - --telemetry.endpoint=/metrics
        ports:
        - name: metrics
          containerPort: 9117
        {{- with .Values.sidecar.metrics.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.metrics.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_services_rendering.labels.app" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_services_rendering.labels.app" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: file
        configMap:
          name: {{ include "edusharing_services_rendering.name" . }}-file
      - name: share-config
        persistentVolumeClaim:
          claimName: {{ include "edusharing_services_rendering.pvc.share.config" . }}
      - name: share-data
        persistentVolumeClaim:
          claimName: {{ include "edusharing_services_rendering.pvc.share.data" . }}
