version: '3.7'

services:

  cache:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-redis:${docker.tag}"

  profiler:
    image: "${docker.registry}/${docker.repository}/${docker.prefix}-deploy-docker-build-profiler:${docker.tag}"
