version: '3.7'

services:

  repository-database:
    restart: unless-stopped

  repository-mailcatcher:
    restart: unless-stopped

  repository-search-solr6:
    restart: unless-stopped

  repository-service:
    restart: unless-stopped

  repository-transform:
    restart: unless-stopped

  repository-alfresco-transform-core-aio:
    restart: unless-stopped

  repository-transform-edu-sharing:
    restart: unless-stopped

  repository-activemq:
    restart: unless-stopped