version: '3.7'

services:

  repository-cache:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.redis.name}:${docker.edu_sharing.community.common.redis.tag}"
    container_name: "repository-cache_${COMPOSE_PROJECT_NAME}"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - 6379

  repository-database:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.postgresql.name}:${docker.edu_sharing.community.common.postgresql.tag}"
    container_name: "repository-database_${COMPOSE_PROJECT_NAME}"
    environment:
      POSTGRESQL_DATABASE: "${REPOSITORY_DATABASE_NAME:-repository}"
      POSTGRESQL_PASSWORD: "${REPOSITORY_DATABASE_PASS:-repository}"
      POSTGRESQL_POSTGRES_PASSWORD: "${REPOSITORY_DATABASE_PASS:-repository}"
      POSTGRESQL_USERNAME: "${REPOSITORY_DATABASE_USER:-repository}"
    expose:
      - "5432"
    shm_size: 256m
    volumes:
      - "repository-database-volume-data:/bitnami/postgresql"

  repository-mailcatcher:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.mailcatcher.name}:${docker.edu_sharing.community.common.mailcatcher.tag}"
    container_name: "repository-mailcatcher_${COMPOSE_PROJECT_NAME}"
    expose:
      - "1025"
      - "1080"

  repository-search-solr:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.alfresco.search.service.name}:${docker.edu_sharing.community.common.alfresco.search.service.tag}"
    container_name: "repository-search-solr_${COMPOSE_PROJECT_NAME}"
    command:
      - solr/solr/bin/solr
      - start
      - -f
      - -p
      - "8080"
      - -a
      - -javaagent:/opt/alfresco/solr/agent/jmx_prometheus_javaagent.jar=9090:/opt/alfresco/solr/agent/jmx-exporter-config.yaml
      - -Dcreate.alfresco.defaults=alfresco,archive
    environment:
      REPOSITORY_SEARCH_SOLR_ENVS: >-
        ENABLE_REMOTE_JMX_OPTS="true"
        RMI_PORT="7199"
        GC_TUNE="-XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+AlwaysPreTouch -XX:+ExplicitGCInvokesConcurrent"
        SOLR_JAVA_MEM="-Xms${REPOSITORY_SEARCH_SOLR_JAVA_XMS:-1g} -Xmx${REPOSITORY_SEARCH_SOLR_JAVA_XMX:-1g}"
      REPOSITORY_SEARCH_SOLR_HOST: repository-search-solr
      REPOSITORY_SEARCH_SOLR_PORT: "8080"
      REPOSITORY_SERVICE_HOST: repository-service
      REPOSITORY_SERVICE_PORT: "8080"
    expose:
      - "7199"
      - "8080"
      - "9090"
    volumes:
      - "repository-search-solr-volume-data:/opt/alfresco/alf_data"
    depends_on:
      - repository-service

  repository-alfresco-share:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.alfresco.share.name}:${docker.edu_sharing.community.common.alfresco.share.tag}"
    container_name: "repository-alfresco-share_${COMPOSE_PROJECT_NAME}"
    environment:
      REPO_HOST: repository-service
      REPO_PORT: 8080
    expose:
      - "8080"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_ALFRESCO_SHARE_PORT_HTTP:-8103}:8080"
    depends_on:
      - repository-service

  repository-service:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-service:${docker.tag}"
    container_name: "repository-service_${COMPOSE_PROJECT_NAME}"
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      CACHE_CLUSTER: "false"
      CACHE_DATABASE: "0"
      CACHE_HOST: repository-cache
      CACHE_PORT: "6379"
      CATALINA_OPTS: >-
        -Xms${REPOSITORY_SERVICE_JAVA_XMS:-2g}
        -Xmx${REPOSITORY_SERVICE_JAVA_XMX:-4g}
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.port=7199
        -Dcom.sun.management.jmxremote.ssl=false
        -javaagent:/opt/alfresco/tomcat/agent/jmx_prometheus_javaagent.jar=9090:/opt/alfresco/tomcat/agent/jmx-exporter-config.yaml
      REPOSITORY_DATABASE_HOST: repository-database
      REPOSITORY_DATABASE_NAME: "${REPOSITORY_DATABASE_NAME:-repository}"
      REPOSITORY_DATABASE_PASS: "${REPOSITORY_DATABASE_PASS:-repository}"
      REPOSITORY_DATABASE_PORT: "5432"
      REPOSITORY_DATABASE_USER: "${REPOSITORY_DATABASE_USER:-repository}"
      REPOSITORY_SEARCH_SOLR_HOST: repository-search-solr
      REPOSITORY_SEARCH_SOLR_PORT: "8080"
      REPOSITORY_SERVICE_ADMIN_PASS: "${REPOSITORY_SERVICE_ADMIN_PASS:-admin}"
      REPOSITORY_SERVICE_GUEST_PASS: "${REPOSITORY_SERVICE_GUEST_PASS:-}"
      REPOSITORY_SERVICE_GUEST_USER: "${REPOSITORY_SERVICE_GUEST_USER:-}"
      REPOSITORY_SERVICE_HOME_APPID: "${REPOSITORY_SERVICE_HOME_APPID:-${COMPOSE_PROJECT_NAME:-local}}"
      REPOSITORY_SERVICE_HOME_AUTH: "${REPOSITORY_SERVICE_AUTH:-}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL: "${REPOSITORY_SERVICE_AUTH_EXTERNAL:-false}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGIN: "${REPOSITORY_SERVICE_AUTH_EXTERNAL_LOGIN:-}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT: "${REPOSITORY_SERVICE_AUTH_EXTERNAL_LOGOUT:-}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_DESTROY_SESSION: "${REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_DESTROY_SESSION:-false}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_REDIRECT: "${REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_REDIRECT:-}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_REDIRECT_URL: "${REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGOUT_REDIRECT_URL:-}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGIN_PROVIDERS_URL: "${REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGIN_PROVIDERS_URL:-}"
      REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGIN_PROVIDER_TARGET_URL: "${REPOSITORY_SERVICE_HOME_AUTH_EXTERNAL_LOGIN_PROVIDER_TARGET_URL:-}"
      REPOSITORY_SERVICE_HOME_PROVIDER: "${REPOSITORY_SERVICE_PROVIDER:-}"
      REPOSITORY_SERVICE_HOME_URL_DYNAMIC: "${REPOSITORY_SERVICE_HOME_URL_DYNAMIC:-}"
      REPOSITORY_SERVICE_ALLOW_ORIGIN: "${REPOSITORY_SERVICE_ALLOW_ORIGIN:-}"
      REPOSITORY_SERVICE_HOST_EXTERNAL: "${REPOSITORY_SERVICE_HOST:-repository.127.0.0.1.nip.io}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_CONNECT: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_CONNECT:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_DEFAULT: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_DEFAULT:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_FONT: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_FONT:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_FRAME: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_FRAME:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_IMG: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_IMG:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_MEDIA: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_MEDIA:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_OBJECT: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_OBJECT:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_SCRIPT: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_SCRIPT:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_CSP_STYLE: "${REPOSITORY_SERVICE_HTTP_SERVER_CSP_STYLE:-}"
      REPOSITORY_SERVICE_HTTP_SERVER_SESSION_TIMEOUT: "${REPOSITORY_SERVICE_HTTP_SERVER_SESSION_TIMEOUT:-60}"
      REPOSITORY_SERVICE_MAIL_FROM: "${REPOSITORY_SERVICE_MAIL_FROM:-no-reply@edu-sharing.net}"
      REPOSITORY_SERVICE_MAIL_ADDREPLYTO: "${REPOSITORY_SERVICE_MAIL_ADDREPLYTO:-true}"
      REPOSITORY_SERVICE_MAIL_REGISTER_RECEIVER: "${REPOSITORY_SERVICE_MAIL_REGISTER_RECEIVER:-}"
      REPOSITORY_SERVICE_MAIL_REPORT_RECEIVER: "${REPOSITORY_SERVICE_MAIL_REPORT_RECEIVER:-}"
      REPOSITORY_SERVICE_MAIL_SERVER_SMTP_HOST: "${REPOSITORY_SERVICE_MAIL_SERVER_SMTP_HOST:-repository-mailcatcher}"
      REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PORT: "${REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PORT:-1025}"
      REPOSITORY_SERVICE_MAIL_SERVER_SMTP_USERNAME: "${REPOSITORY_SERVICE_MAIL_SERVER_SMTP_USERNAME:-}"
      REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PASSWORD: "${REPOSITORY_SERVICE_MAIL_SERVER_SMTP_PASSWORD:-}"
      REPOSITORY_SERVICE_MAIL_SERVER_SMTP_AUTHTYPE: "${REPOSITORY_SERVICE_MAIL_SERVER_SMTP_AUTHTYPE:-}"
      REPOSITORY_SERVICE_PATH_EXTERNAL: "${REPOSITORY_SERVICE_PATH:-/edu-sharing}"
      REPOSITORY_SERVICE_PORT_EXTERNAL: "${REPOSITORY_SERVICE_PORT:-8100}"
      REPOSITORY_SERVICE_PROT_EXTERNAL: "${REPOSITORY_SERVICE_PROT:-http}"
      REPOSITORY_SERVICE_POOL_EXTERNAL: "${REPOSITORY_SERVICE_POOL_EXTERNAL:-200}"
      REPOSITORY_SERVICE_WAIT_EXTERNAL: "${REPOSITORY_SERVICE_WAIT_EXTERNAL:--1}"
      REPOSITORY_SERVICE_PROXY_BUFFER_SIZE: "${REPOSITORY_SERVICE_PROXY_BUFFER_SIZE:-65536}"
      REPOSITORY_SERVICE_HOST_INTERNAL: repository-service
      REPOSITORY_SERVICE_PORT_INTERNAL: "8080"
      REPOSITORY_SERVICE_POOL_INTERNAL: "${REPOSITORY_SERVICE_POOL_INTERNAL:-200}"
      REPOSITORY_SERVICE_WAIT_INTERNAL: "${REPOSITORY_SERVICE_WAIT_INTERNAL:--1}"
      REPOSITORY_SERVICE_HTTP_CLIENT_PROXY_NONPROXYHOSTS: "${NON_PROXY_HOST:-}"
      REPOSITORY_SERVICE_HTTP_CLIENT_PROXY_HOST: "${PROXY_HOST:-}"
      REPOSITORY_SERVICE_HTTP_CLIENT_PROXY_PROXYPORT: "${PROXY_PORT:-}"
      REPOSITORY_SERVICE_HTTP_CLIENT_PROXY_PROXYUSER: "${PROXY_USER:-}"
      REPOSITORY_SERVICE_HTTP_CLIENT_PROXY_PROXYPASS: "${PROXY_PASS:-}"
      REPOSITORY_TRANSFORM_ENABLED: "${REPOSITORY_SERVICE_TRANSFORM_ENABLED:-true}"
      REPOSITORY_TRANSFORM_HOST: repository-transform
      REPOSITORY_TRANSFORM_PORT: "8100"
      REPOSITORY_TRANSFORM_AIO_HOST: repository-transform-core-aio
      REPOSITORY_TRANSFORM_AIO_PORT: "8090"
      REPOSITORY_TRANSFORM_ES_HOST: repository-transform-edu-sharing
      REPOSITORY_TRANSFORM_ES_PORT: "8091"
      TOMCAT_INSTALL_DEFAULT_WEBAPPS: "no"
    expose:
      - "7199"
      - "8080"
      - "9090"
    ports:
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SERVICE_PORT_AJP:-8102}:8009"
      - "${COMMON_BIND_HOST:-127.0.0.1}:${REPOSITORY_SERVICE_PORT_HTTP:-8100}:8081"
    volumes:
      - "repository-service-volume-config-cluster:/opt/bitnami/tomcat/shared/classes/config/cluster"
      - "repository-service-volume-config-node:/opt/bitnami/tomcat/shared/classes/config/node"
      - "repository-service-volume-data:/opt/alfresco/alf_data"
      - "repository-service-volume-safe:/opt/alfresco/alf_safe"
    depends_on:
      - repository-database
      - repository-transform

  repository-transform:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.alfresco.transform.name}:${docker.edu_sharing.community.common.alfresco.transform.tag}"
    container_name: "repository-transform_${COMPOSE_PROJECT_NAME}"
    expose:
      - "8100"

  repository-transform-core-aio:
    image: "${docker.registry}/${docker.common}/${docker.edu_sharing.community.common.alfresco.transform.core.aio.name}:${docker.edu_sharing.community.common.alfresco.transform.core.aio.tag}"
    container_name: "repository-transform-core-aio_${COMPOSE_PROJECT_NAME}"
    expose:
      - "8090"

  repository-transform-edu-sharing:
    image: "${docker.repository}/${docker.prefix}-deploy-docker-build-transform-edu-sharing:${docker.tag}"
    container_name: "repository-transform-edu-sharing_${COMPOSE_PROJECT_NAME}"
    expose:
      - "8091"

volumes:
  repository-database-volume-data:
  repository-search-solr-volume-data:
  repository-search-solr-volume-solrhome:
  repository-service-volume-config-cluster:
  repository-service-volume-config-node:
  repository-service-volume-data:
  repository-service-volume-safe:
