apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}-file
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.config.override.config.application.settings }}
  config-application-settings: | {{ . | nindent 4 }}
{{- end }}

