apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_common_lib.names.name" . }}
  labels: {{ include "edusharing_common_lib.labels.app" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_common_lib.labels.app" . | nindent 6 }}
  serviceName: {{ include "edusharing_common_lib.names.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_common_lib.names.name" . }}
      labels: {{ include "edusharing_common_lib.labels.app" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        checksum/secret-file: {{ include (print .Template.BasePath "/secret-file.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        prometheus.io/scrape: {{ .Values.config.metrics.enabled | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- with merge .Values.podAnnotations .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if (default .Values.global.cluster.storage.share.permission .Values.persistence.share.permission) }}
      - name: {{ include "edusharing_common_lib.names.name" . }}-init-permission
        image: {{ include "edusharing_common_lib.images.common" . }}{{ .Values.init.permission.image.name }}:{{ .Values.init.permission.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          if [[ ! "$(ls -A /opt/bitnami/tomcat/shared/classes/config/cluster)" ]]; then
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /opt/bitnami/tomcat/shared/classes/config/cluster
          fi
          if [[ ! "$(ls -A /opt/bitnami/tomcat/shared/classes/config/node)" ]]; then
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /opt/bitnami/tomcat/shared/classes/config/node
          fi
          if [[ ! "$(ls -A /opt/alfresco/alf_data)" ]]; then
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /opt/alfresco/alf_data
          fi
          {{- if .Values.persistence.share.safe.enabled }}
          if [[ ! "$(ls -A /opt/alfresco/alf_safe)" ]]; then
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /opt/alfresco/alf_safe
          fi
          {{- end }}
        volumeMounts:
        - name: data
          mountPath: /opt/bitnami/tomcat/shared/classes/config/node
        - name: share-config
          mountPath: /opt/bitnami/tomcat/shared/classes/config/cluster
        - name: share-data
          mountPath: /opt/alfresco/alf_data
        {{- if .Values.persistence.share.safe.enabled }}
        - name: share-safe
          mountPath: /opt/alfresco/alf_safe
        {{- end }}
        {{- with .Values.init.permission.startupProbe }}
        startupProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo startupProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.init.permission.livenessProbe }}
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo livenessProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.init.permission.readinessProbe }}
        readinessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo readinessProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.init.permission.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.permission.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_common_lib.names.name" . }}-server
        image: {{ include "edusharing_common_lib.images.image" . }}{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        env:
          - name: REPOSITORY_SERVICE_JOBS_PRIMARY_HOSTNAME
            value: {{ include "edusharing_common_lib.names.name" . }}-0
          {{- $patroni := merge .Values.config.database.patroni .Values.global.patroni }}
          {{- if $patroni.enabled }}
          - name: REPOSITORY_DATABASE_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.config.database.username }}.{{ $patroni.name }}.{{ $patroni.secrets }}
                key: password
          {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_common_lib.names.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_common_lib.names.name" . }}-env
        ports:
        - name: api-internal
          containerPort: 8080
        - name: api-external
          containerPort: 8081
        - name: gossip
          containerPort: 5701
        {{- if .Values.config.metrics.enabled }}
        - name: metrics-api
          containerPort: 9090
        {{- end }}
        {{- if default .Values.global.debug .Values.debug }}
        - name: jpda
          containerPort: 5005
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /opt/bitnami/tomcat/shared/classes/config/node
        - name: share-config
          mountPath: /opt/bitnami/tomcat/shared/classes/config/cluster
        - name: share-data
          mountPath: /opt/alfresco/alf_data
        {{- with .Values.config.override.config.application.client }}
        - name: file
          mountPath: /opt/bitnami/tomcat/shared/classes/config/defaults/client.config.override.xml
          subPath: config-application-client
        {{- end }}
        {{- with .Values.config.override.config.application.mds }}
        - name: file
          mountPath: /opt/bitnami/tomcat/shared/classes/config/defaults/metadatasets/xml/mds_override.xml
          subPath: config-application-mds
        {{- end }}
        {{- with .Values.config.override.config.application.settings }}
        - name: file-sec
          mountPath: /opt/bitnami/tomcat/shared/classes/config/defaults/edu-sharing.override.conf
          subPath: config-application-settings
        {{- end }}
        {{- with .Values.config.override.logging.application }}
        - name: file
          mountPath: /opt/bitnami/tomcat/webapps/alfresco/WEB-INF/log4j2-alfresco.properties
          subPath: logging-application
        {{- end }}
        {{- with .Values.config.override.logging.server }}
        - name: file
          mountPath: /opt/bitnami/tomcat/conf/logging.properties
          subPath: logging-server
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe:
          httpGet:
            path: /edu-sharing/rest/_about/status/SERVICE?timeoutSeconds={{ .timeoutSeconds }}
            httpHeaders:
              - name: Accept
                value: application/json
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /edu-sharing/rest/_about/status/SERVICE?timeoutSeconds={{ .timeoutSeconds }}
            httpHeaders:
            - name: Accept
              value: application/json
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{ if not .Values.config.transform.server.enabled }}
      - name: {{ include "edusharing_common_lib.names.name" . }}-transform
        image: {{ include "edusharing_common_lib.images.common" . }}{{ .Values.sidecar.transform.image.name }}:{{ .Values.sidecar.transform.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_common_lib.names.name" . }}-env
        ports:
        - name: api
          containerPort: 8100
        {{- with .Values.sidecar.transform.startupProbe }}
        startupProbe:
          exec:
            command:
              - "/bin/bash"
              - "-ec"
              - |
                unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.transform.livenessProbe }}
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.transform.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.transform.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.transform.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{ if .Values.proxy.enabled }}
      - name: {{ include "edusharing_common_lib.names.name" . }}-proxy
        image: {{ include "edusharing_common_lib.images.common" . }}{{ .Values.sidecar.proxyCache.image.name }}:{{ .Values.sidecar.proxyCache.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args:
          - '-F'
          - '-f'
          - /etc/varnish/default.vcl
          - '-T'
          - 127.0.0.1:6082
          - '-a'
          - 0.0.0.0:6081
        ports:
        - name: api-proxy
          containerPort: 6081
        volumeMounts:
        - name: file
          mountPath: /etc/varnish/default.vcl
          subPath: proxy-config
        - name: temp-proxy
          mountPath: /var/lib/varnish
        {{- with .Values.sidecar.proxyCache.startupProbe }}
        startupProbe:
          httpGet:
            path: /health/ready
            port: api-proxy
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.livenessProbe }}
        livenessProbe:
          exec:
            command:
              - /usr/bin/varnishadm
              - ping
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /health/ready
            port: api-proxy
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.proxyCache.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.config.metrics.enabled }}
      - name: {{ include "edusharing_common_lib.names.name" . }}-proxy-metrics
        image: {{ include "edusharing_common_lib.images.common" . }}{{ .Values.sidecar.proxyMetrics.image.name }}:{{ .Values.sidecar.proxyMetrics.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        ports:
        - name: metrics-proxy
          containerPort: 9131
        volumeMounts:
          - name: file
            mountPath: /etc/varnish/default.vcl
            subPath: proxy-config
          - name: temp-proxy
            mountPath: /var/lib/varnish
        {{- with .Values.sidecar.proxyMetrics.startupProbe }}
        startupProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo startupProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.livenessProbe }}
        livenessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo livenessProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.readinessProbe }}
        readinessProbe:
          exec:
            command:
              - "/bin/sh"
              - "-c"
              - "echo readinessProbe > /dev/null"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.proxyMetrics.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge .Values.podSecurityContext .Values.global.security }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_common_lib.labels.app" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_common_lib.labels.app" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: share-config
        persistentVolumeClaim:
          claimName: {{ include "edusharing_repository_service.pvc.share.config" . }}
      - name: share-data
        persistentVolumeClaim:
          claimName: {{ include "edusharing_repository_service.pvc.share.data" . }}
      {{- if .Values.persistence.share.safe.enabled }}
      - name: share-safe
        persistentVolumeClaim:
          claimName: {{ include "edusharing_repository_service.pvc.share.safe" . }}
      {{- end }}
      - name: file
        configMap:
          name: {{ include "edusharing_common_lib.names.name" . }}-file
      - name: file-sec
        secret:
          secretName: {{ include "edusharing_common_lib.names.name" . }}-file
      {{- if .Values.proxy.enabled }}
      - name: temp-proxy
        emptyDir: { }
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_common_lib.labels.app" . | nindent 8 }}
    spec: {{ merge .Values.persistence.data.config.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}