{{- if .Values.global.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "edusharing.name" . }}-prometheus
  labels: {{ include "edusharing.labels.app" . | nindent 4 }}
{{- end }}
