{{- if .Values.persistence.share.config.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "edusharing_repository_service.pvc.share.config" . }}
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec: {{ merge .Values.persistence.share.config.spec .Values.global.cluster.storage.share.spec | toYaml | nindent 2 }}
{{- end }}
{{- if .Values.persistence.share.data.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "edusharing_repository_service.pvc.share.data" . }}
  labels: {{ include "edusharing_repository_service.labels.app" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec: {{ merge .Values.persistence.share.data.spec .Values.global.cluster.storage.share.spec | toYaml | nindent 2 }}
{{- end }}
