{{- if .Values.global.cluster.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_repository_search_solr.name" . }}
  labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 6 }}
      {{- if .Values.multistage.enabled }}
      app.kubernetes.io/stage: ""
      {{- end }}
{{- if .Values.multistage.enabled }}
{{- range .Values.multistage.stages }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_repository_search_solr.name" $ }}-{{ .name }}
  labels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 6 }}
      app.kubernetes.io/stage: {{ .name }}
{{- end }}
{{- end }}
{{- end }}