apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_search_solr.name" . }}
  labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: {{ .Values.multistage.current | quote }}
    {{- end }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_search_solr.name" . }}-headless
  labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
{{- if and .Values.global.metrics.servicemonitor.enabled .Values.config.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_search_solr.name" . }}-metrics
  labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics"
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
  ports:
    - name: http-metrics
      port: {{ .Values.service.port.metrics }}
      targetPort: metrics
{{- end }}
{{- if .Values.multistage.enabled }}
{{- range .Values.multistage.stages }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_search_solr.name" $ }}-headless-{{ .name }}
  labels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
  ports:
  - name: http-api
    port: {{ $.Values.service.port.api }}
{{- if and $.Values.global.metrics.servicemonitor.enabled $.Values.config.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_search_solr.name" $ }}-metrics-{{ .name }}
  labels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 4 }}
    app.kubernetes.io/component: "metrics"
    app.kubernetes.io/stage: {{ .name }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
  ports:
  - name: http-metrics
    port: {{ $.Values.service.port.metrics }}
    targetPort: metrics
{{- end }}
{{- end }}
{{- end }}