apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_repository_search_solr.name" . }}
  labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 4 }}
    {{- if .Values.multistage.enabled }}
    app.kubernetes.io/stage: ""
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 6 }}
      {{- if .Values.multistage.enabled }}
      app.kubernetes.io/stage: ""
      {{- end }}
  serviceName: {{ include "edusharing_repository_search_solr.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_repository_search_solr.name" . }}
      labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 8 }}
         {{- if .Values.multistage.enabled }}
        app.kubernetes.io/stage: ""
         {{- end }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        prometheus.io/scrape: {{ .Values.config.metrics.enabled | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- with merge .Values.podAnnotations .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if (default .Values.global.cluster.storage.data.permission .Values.persistence.data.permission) }}
      - name: {{ include "edusharing_repository_search_solr.name" . }}-init-permission
        image: {{ .Values.images.minideb }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command:
            - "/bin/bash"
            - "-ec"
            - |
              if [[ ! "$(ls -A /opt/alfresco/alf_data)" ]]; then
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /opt/alfresco/alf_data
              fi
          volumeMounts:
            - name: data
              mountPath: /opt/alfresco/alf_data
        {{- with .Values.init.permission.resources }}
          resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.permission.securityContext }}
          securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_repository_search_solr.name" . }}
        image {{ .Values.images.alfresco.search.service }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- if default .Values.global.debug .Values.debug }}
          args: [ "catalina.sh", "jpda", "run" ]
        {{- end }}
          envFrom:
            - configMapRef:
            name: {{ include "edusharing_repository_search_solr.name" . }}-env
          ports:
            - name: api
              containerPort: 8080
        {{- if .Values.config.metrics.enabled }}
            - name: metrics
              containerPort: 9090
        {{- end }}
        {{- if default .Values.global.debug .Values.debug }}
            - name: jpda
              containerPort: 5005
        {{- end }}
          volumeMounts:
            - name: data
              mountPath: /opt/alfresco/alf_data
        {{- with .Values.config.override.logging.application }}
            - name: file
              mountPath: /opt/alfresco/solr/log4j.properties
              subPath: logging-application
        {{- end }}
        {{- with .Values.config.override.logging.server }}
            - name: file
              mountPath: /opt/bitnami/tomcat/conf/logging.properties
              subPath: logging-server
        {{- end }}
        {{- with .Values.startupProbe }}
          startupProbe:
            httpGet:
            path: /solr
              port: api
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            successThreshold: {{ .successThreshold }}
            timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
          livenessProbe:
            tcpSocket:
              port: api
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
          readinessProbe:
            httpGet:
            path: /solr
              port: api
            failureThreshold: {{ .failureThreshold }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            successThreshold: {{ .successThreshold }}
            timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge .Values.podSecurityContext .Values.global.security }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
              matchLabels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 16 }}
                {{- if .Values.multistage.enabled }}
                app.kubernetes.io/stage: ""
                {{- end }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                matchLabels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 18 }}
                  {{- if .Values.multistage.enabled }}
                  app.kubernetes.io/stage: ""
                  {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
        - name: file
          configMap:
            name: {{ include "edusharing_repository_search_solr.name" . }}-file
  volumeClaimTemplates:
    - metadata:
        name: data
      labels: {{ include "edusharing_repository_search_solr.labels.app" . | nindent 8 }}
      spec: {{ merge .Values.persistence.data.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}
{{- if .Values.multistage.enabled }}
{{- range .Values.multistage.stages }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_repository_search_solr.name" $ }}-{{ .name }}
  labels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 4 }}
    app.kubernetes.io/stage: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 6 }}
      app.kubernetes.io/stage: {{ .name }}
  serviceName: {{ include "edusharing_repository_search_solr.name" $ }}-headless-{{ .name }}
  template:
    metadata:
      name: {{ include "edusharing_repository_search_solr.name" $ }}
      labels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 8 }}
        app.kubernetes.io/stage: {{ .name }}
      annotations:
        checksum/configmap-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") $ | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print $.Template.BasePath "/configmap-file.yaml") $ | sha256sum | trunc 63 }}
        {{- if not $.Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        prometheus.io/scrape: {{ $.Values.config.metrics.enabled | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ $.Values.global.cluster.istio.enabled | quote }}
        {{- with merge $.Values.podAnnotations $.Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if (default $.Values.global.cluster.storage.data.permission $.Values.persistence.data.permission) }}
      - name: {{ include "edusharing_repository_search_solr.name" $ }}-init-permission
        image: {{ include "edusharing_repository_search_solr.image" $ }}{{ $.Values.images.minideb }}
        imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            if [[ ! "$(ls -A /opt/alfresco/alf_data)" ]]; then
              chown -R {{ $.Values.securityContext.runAsUser }}:{{ $.Values.podSecurityContext.fsGroup }} /opt/alfresco/alf_data
            fi
        volumeMounts:
          - name: data
            mountPath: /opt/alfresco/alf_data
        {{- with $.Values.init.permission.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $.Values.init.permission.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_repository_search_solr.name" $ }}
        image: {{ include "edusharing_repository_search_solr.image" $ }}{{ $.Values.images.alfresco.search.service }}
        imagePullPolicy: {{ $.Values.global.image.pullPolicy }}
        {{- if default $.Values.global.debug $.Values.debug }}
        args: [ "catalina.sh", "jpda", "run" ]
        {{- end }}
        env:
        - name: REPOSITORY_SEARCH_SOLR_CONFIG
          value: | {{ .spec.config.override.application.common | nindent 12 }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_search_solr.name" $ }}-env
        ports:
        - name: api
          containerPort: 8080
        {{- if $.Values.config.metrics.enabled }}
        - name: metrics
          containerPort: 9090
        {{- end }}
        {{- if default $.Values.global.debug $.Values.debug }}
        - name: jpda
          containerPort: 5005
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /opt/alfresco/alf_data
        {{- with $.Values.config.override.logging.application }}
        - name: file
          mountPath: /opt/alfresco/solr/log4j.properties
          subPath: logging-application
        {{- end }}
        {{- with $.Values.config.override.logging.server }}
        - name: file
          mountPath: /opt/bitnami/tomcat/conf/logging.properties
          subPath: logging-server
        {{- end }}
        {{- with $.Values.startupProbe }}
        startupProbe:
          httpGet:
            path: /solr
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with $.Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with $.Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /solr
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with $.Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with $.Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with $.Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge $.Values.podSecurityContext $.Values.global.security }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with $.Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or $.Values.nodeAffinity $.Values.podAntiAffinity }}
      affinity:
        {{- with $.Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if $.Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq $.Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 16 }}
                app.kubernetes.io/stage: {{ .name }}
          {{- else if eq $.Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 18 }}
                  app.kubernetes.io/stage: {{ .name }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: file
        configMap:
          name: {{ include "edusharing_repository_search_solr.name" $ }}-file
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_repository_search_solr.labels.app" $ | nindent 8 }}
    spec: {{ merge $.Values.persistence.data.spec $.Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}
{{- end }}
{{- end }}