apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_rediscluster.name" . }}
  labels: {{ include "edusharing_rediscluster.labels.app" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ include "edusharing_rediscluster.replicas" . }}
  selector:
    matchLabels: {{ include "edusharing_rediscluster.labels.app" . | nindent 6 }}
  serviceName: {{ include "edusharing_rediscluster.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_rediscluster.name" . }}
      labels: {{ include "edusharing_rediscluster.labels.app" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9114"
        prometheus.io/scrape: {{ .Values.sidecar.metrics.enabled | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if (default .Values.global.cluster.storage.data.permission .Values.persistence.data.permission) }}
      - name: {{ include "edusharing_rediscluster.name" . }}-init-permission
        image: {{ include "edusharing_rediscluster.image" . }}{{ .Values.image.prefix }}-deploy-docker-build-minideb:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /bitnami/redis
        volumeMounts:
        - name: data
          mountPath: /bitnami/redis
        {{- with .Values.init.permission.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.permission.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_rediscluster.name" . }}
        image: {{ include "edusharing_rediscluster.image" . }}{{ .Values.image.prefix }}-deploy-docker-build-rediscluster:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
          - "/bin/bash"
          - "-ec"
          - |
            [[ -f /opt/bitnami/redis/etc/redis.conf ]] || {
              cp /opt/bitnami/redis/etc/redis-default.conf /opt/bitnami/redis/etc/redis.conf
            }
            if [[ "${HOSTNAME##*-}" == "0" ]]; then
              export REDIS_CLUSTER_CREATOR="yes"
            fi
            /opt/bitnami/scripts/redis-cluster/entrypoint.sh /opt/bitnami/scripts/redis-cluster/run.sh
        env:
          - name: REDIS_CLUSTER_ANNOUNCE_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_rediscluster.name" . }}-env
        ports:
        - name: api
          containerPort: 6379
        - name: gossip
          containerPort: 16379
        volumeMounts:
        - name: data
          mountPath: /bitnami/redis
        - name: file
          mountPath: /opt/bitnami/redis/etc/redis-default.conf
          subPath: redis-default.conf
        {{- with .Values.startupProbe }}
        startupProbe:
          exec:
            command:
              - "/bin/bash"
              - "-ec"
              - |
                [[ $(redis-cli ping) == "PONG" && $(redis-cli CLUSTER INFO | grep cluster_state | tr -d '[:space:]') == "cluster_state:ok" ]] || exit 1
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          exec:
            command:
              - "/bin/bash"
              - "-ec"
              - |
                [[ $(redis-cli ping) == "PONG" || $(redis-cli ping | head -n1 | awk '{print $1;}') =~ ^LOADING$|^MASTERDOWN$ ]] || exit 1
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              [[ $(redis-cli ping) == "PONG" && $(redis-cli CLUSTER INFO | grep cluster_state | tr -d '[:space:]') == "cluster_state:ok" ]] || exit 1
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.sidecar.metrics.enabled }}
      - name: {{ include "edusharing_rediscluster.name" . }}-metrics
        image: {{ include "edusharing_rediscluster.image" . }}{{ .Values.image.prefix }}-deploy-docker-build-redis_exporter:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args:
        - --redis.addr=redis://127.0.0.1:6379
        - --web.listen-address=:9114
        - --web.telemetry-path=/metrics
        ports:
        - name: metrics
          containerPort: 9114
        {{- with .Values.sidecar.metrics.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.metrics.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_rediscluster.labels.app" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_rediscluster.labels.app" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: file
        configMap:
          name: {{ include "edusharing_rediscluster.name" . }}-file
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_rediscluster.labels.app" . | nindent 8 }}
    spec: {{ merge .Values.persistence.data.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}
