{{- if not .Values.global.patroni.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "edusharing_postgresql.name" . }}-file
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
data:
  extended.conf: |
    {{- range $key, $value := .Values.config.extra }}
    {{ $key }} = '{{ $value }}'
    {{- end }}
    listen_addresses = '{{ if .Values.global.cluster.istio.enabled }}127.0.0.1{{ else }}0.0.0.0{{ end }}'
{{- end }}