{{- if not .Values.global.patroni.enabled }}
{{- if .Values.global.cluster.pdb.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "edusharing_postgresql.name" . }}
  labels: {{ include "edusharing_postgresql.labels" . | nindent 4 }}
spec:
  maxUnavailable: 0
  selector:
    matchLabels: {{ include "edusharing_postgresql.labels.instance" . | nindent 6 }}
{{- end }}
{{- end }}