{{- if not .Values.global.patroni.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_postgresql.name" . }}
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
  ports:
  - name: tcp-api
    port: {{ .Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_postgresql.name" . }}-headless
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
  ports:
  - name: tcp-api
    port: {{ .Values.service.port.api }}
{{- if and .Values.global.metrics.servicemonitor.enabled .Values.sidecar.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_postgresql.name" . }}-metrics
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
    app.kubernetes.io/component: "metrics"
spec:
  type: ClusterIP
  selector: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
  ports:
    - name: http-metrics
      port: {{ .Values.service.port.metrics }}
      targetPort: metrics
{{- end }}    
{{- end }}