{{- if not .Values.global.patroni.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_postgresql.name" . }}
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
  ports:
  - name: tcp-api
    port: {{ .Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_postgresql.name" . }}-headless
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
  ports:
  - name: tcp-api
    port: {{ .Values.service.port.api }}
{{- end }}