{{- if not .Values.global.patroni.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_postgresql.name" . }}
  labels: {{ include "edusharing_postgresql.labels.app" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "edusharing_postgresql.labels.app" . | nindent 6 }}
  serviceName: {{ include "edusharing_postgresql.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_postgresql.name" . }}
      labels: {{ include "edusharing_postgresql.labels.app" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        {{- if not .Values.global.metrics.servicemonitor.enabled }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9114"
        prometheus.io/scrape: {{ .Values.sidecar.metrics.enabled | quote }}
        {{- end }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
        {{- with merge .Values.podAnnotations .Values.global.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
      {{- if (default .Values.global.cluster.storage.data.permission .Values.persistence.data.permission) }}
      - name: {{ include "edusharing_postgresql.name" . }}-init-permission
        image: {{ include "edusharing_postgresql.image" . }}{{ .Values.images.minideb }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          if [[ ! "$(ls -A /bitnami/postgresql)" ]]; then
            chown -R {{ .Values.securityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /bitnami/postgresql
          fi
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
        {{- with .Values.init.permission.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.permission.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_postgresql.name" . }}
        image: {{ include "edusharing_postgresql.image" . }}{{ .Values.images.postgres.db }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_postgresql.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_postgresql.name" . }}-env
        ports:
        - name: api
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
        - name: file
          mountPath: /bitnami/postgresql/conf/conf.d/extended.conf
          subPath: extended.conf
        {{- if .Values.config.shmVolume.enabled }}
        - name: dshm
          mountPath: /dev/shm
        {{- end }}
        {{- with .Values.startupProbe }}
        startupProbe:
          exec:
            command:
              - "/bin/bash"
              - "-ec"
              - |
                exec pg_isready -U "${POSTGRESQL_USERNAME}" -d "${POSTGRESQL_DATABASE}"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          exec:
            command:
              - "/bin/bash"
              - "-ec"
              - |
                exec pg_isready -U "${POSTGRESQL_USERNAME}" -d "${POSTGRESQL_DATABASE}"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              exec pg_isready -U "${POSTGRESQL_USERNAME}" -d "${POSTGRESQL_DATABASE}"
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.sidecar.metrics.enabled }}
      - name: {{ include "edusharing_postgresql.name" . }}-metrics
        image: {{ include "edusharing_postgresql.image" . }}{{ .Values.images.postgres.exporter }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args:
        - --disable-settings-metrics
        - --web.listen-address=:9114
        - --web.telemetry-path=/metrics
        envFrom:
        - secretRef:
            name: {{ include "edusharing_postgresql.name" . }}-env
        ports:
        - name: metrics
          containerPort: 9114
        {{- with .Values.sidecar.metrics.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.metrics.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with merge .Values.podSecurityContext .Values.global.security }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.nodeAffinity }}
      affinity:
        nodeAffinity: {{ toYaml . | nindent 10 }}
      {{- end }}
      volumes:
      - name: file
        configMap:
          name: {{ include "edusharing_postgresql.name" . }}-file
      {{- if .Values.config.shmVolume.enabled }}
      - name: dshm
        emptyDir:
          medium: Memory
          {{- with .Values.config.shmVolume.sizeLimit }}
          sizeLimit: {{ . }}
          {{- end }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_postgresql.labels.app" . | nindent 8 }}
    spec: {{ merge .Values.persistence.data.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}
{{- end }}