apiVersion: v1
kind: Secret
metadata:
  name: {{ include "edusharing_postgresql.name" . }}-env
  labels: {{ include "edusharing_postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRESQL_PASSWORD: {{ .Values.config.password | b64enc | quote }}
  POSTGRESQL_POSTGRES_PASSWORD: {{ .Values.config.password | b64enc | quote }}
  POSTGRESQL_USERNAME: {{ .Values.config.username | b64enc | quote }}
