apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_search_solr4.fullname" . }}
  labels: {{ include "edusharing_repository_search_solr4.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{ include "edusharing_repository_search_solr4.labels.instance" . | nindent 4 }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
    targetPort: api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusharing_repository_search_solr4.fullname" . }}-headless
  labels: {{ include "edusharing_repository_search_solr4.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{ include "edusharing_repository_search_solr4.labels.instance" . | nindent 4 }}
  ports:
  - name: http-api
    port: {{ .Values.service.port.api }}
