{{- if not .Values.global.cluster.istio.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "edusharing_rendering_service.name" . }}
  labels: {{ include "edusharing_rendering_service.labels" . | nindent 4 }}
  {{- with merge .Values.ingress.annotations .Values.global.cluster.cert.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.tls }}
  tls: {{ toYaml . | nindent 4 }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      {{- range $.Values.ingress.paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ include "edusharing_rendering_service.name" $ }}
          servicePort: {{ $.Values.service.port.api.external }}
      {{- end }}
  {{- end }}
{{- end }}