apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_elasticsearch.name" . }}
  labels: {{ include "edusharing_elasticsearch.labels" . | nindent 4 }}
spec:
  podManagementPolicy: Parallel
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "edusharing_elasticsearch.labels.instance" . | nindent 6 }}
  serviceName: {{ include "edusharing_elasticsearch.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_elasticsearch.name" . }}
      labels: {{ include "edusharing_elasticsearch.labels" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9114"
        prometheus.io/scrape: {{ .Values.sidecar.metrics.enabled | quote }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
    spec:
      initContainers:
      {{- if .Values.init.permission.enabled }}
      - name: {{ include "edusharing_elasticsearch.name" . }}-init-permission
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/edusharing-minideb:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /usr/share/elasticsearch/data
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
          subPath: data/
        {{- with .Values.init.permission.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.permission.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.init.sysctl.enabled }}
      - name: {{ include "edusharing_elasticsearch.name" . }}-init-sysctl
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/edusharing-minideb:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          sysctl -w vm.max_map_count=262144
        {{- with .Values.init.sysctl.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.init.sysctl.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      containers:
      - name: {{ include "edusharing_elasticsearch.name" . }}
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/edusharing-elasticsearch:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: network.publish_host
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_elasticsearch.name" . }}-env
        ports:
        - name: api
          containerPort: 9200
        - name: gossip
          containerPort: 9300
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
          subPath: data/
        {{- with .Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /_cluster/health?wait_for_status=green&timeout={{ add1 .timeoutSeconds }}s
            port: api
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- if .Values.sidecar.metrics.enabled }}
      - name: {{ include "edusharing_elasticsearch.name" . }}-metrics
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}/edusharing-elasticsearch_exporter:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        args:
        - --es.uri=http://127.0.0.1:9200
        - --es.all
        - --es.indices
        - --es.shards
        - --web.listen-address={{ if .Values.global.cluster.istio.enabled }}127.0.0.1{{ end }}:9114
        - --web.telemetry-path=/metrics
        {{- with .Values.sidecar.metrics.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.sidecar.metrics.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_elasticsearch.labels.instance" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_elasticsearch.labels.instance" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels: {{ include "edusharing_elasticsearch.labels" . | nindent 8 }}
    spec: {{ merge .Values.persistence.data.spec .Values.global.cluster.storage.data.spec | toYaml | nindent 6 }}
