{{- if .Values.global.patroni.enabled }}
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: {{ .Values.global.patroni.name }}
  labels: {{ include "edusharing_postgresql.labels" . | nindent 4 }}
spec:
  databases:
    {{ .Values.config.database }}: {{ .Values.config.username | quote }}
  teamId: {{ .Values.global.patroni.team | quote }}
  users:
    {{ .Values.config.username }}:
      - createdb
  numberOfInstances: {{ .Values.global.patroni.replicas }}
  patroni:
    synchronous_mode: {{ .Values.global.patroni.synchronous.enabled }}
    synchronous_mode_strict: {{ .Values.global.patroni.synchronous.strict }}
  postgresql:
    version: {{ .Values.global.patroni.postgres | quote }}
    parameters: {{ toYaml .Values.config.extra | nindent 6 }}
  volume:
    size: {{ .Values.persistence.data.spec.resources.requests.storage }}
    {{- if or .Values.global.cluster.storage.data.spec.storageClassName .Values.persistence.data.spec.storageClassName }}
    storageClass: {{ default .Values.global.cluster.storage.data.spec.storageClassName .Values.persistence.data.spec.storageClassName }}
    {{- end }}
  {{- with .Values.resources }}
  resources: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}