apiVersion: v2

name: ${helm.prefix}-transform-aio
description: ${helm.prefix}-transform-aio

icon: ${helm.chart.icon}

version: ${helm.chart.version}
appVersion: ${docker.tag}
kubeVersion: "${helm.kube.version}"

dependencies:
  - name: edu_sharing-community-common-lib
    repository: ${helm.deploy.url}
    version: 1.x.x
