apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "edusharing_repository_service.name" . }}
  labels: {{ include "edusharing_repository_service.labels" . | nindent 4 }}
spec:
  replicas: {{ if .Values.config.cluster.enabled }}{{ .Values.replicaCount }}{{ else }}1{{ end }}
  selector:
    matchLabels: {{ include "edusharing_repository_service.labels.instance" . | nindent 6 }}
  serviceName: {{ include "edusharing_repository_service.name" . }}-headless
  template:
    metadata:
      name: {{ include "edusharing_repository_service.name" . }}
      labels: {{ include "edusharing_repository_service.labels" . | nindent 8 }}
      annotations:
        checksum/configmap-env: {{ include (print .Template.BasePath "/configmap-env.yaml") . | sha256sum | trunc 63 }}
        checksum/configmap-file: {{ include (print .Template.BasePath "/configmap-file.yaml") . | sha256sum | trunc 63 }}
        {{- if .Values.config.saml.enabled }}
        {{- if .Values.config.saml.config }}
        checksum/configmap-saml-file: {{ include (print .Template.BasePath "/configmap-saml-file.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
        {{- if .Values.config.saml.files }}
        checksum/configmap-saml-files: {{ include (print .Template.BasePath "/configmap-saml-files.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
        {{- end }}
        checksum/secret-env: {{ include (print .Template.BasePath "/secret-env.yaml") . | sha256sum | trunc 63 }}
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9090"
        prometheus.io/scrape: {{ .Values.metrics.enabled | quote }}
        sidecar.istio.io/inject: {{ .Values.global.cluster.istio.enabled | quote }}
    spec:
      initContainers:
      - name: {{ include "edusharing_repository_service.name" . }}-init-permission
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-minideb:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command:
        - "/bin/bash"
        - "-ec"
        - |
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /usr/local/alfresco/alf_data
          chown -R {{ .Values.podSecurityContext.runAsUser }}:{{ .Values.podSecurityContext.fsGroup }} /usr/local/alfresco/tomcat/shared
        volumeMounts:
        - name: share
          mountPath: /usr/local/alfresco/alf_data
          subPath: data/
        - name: share
          mountPath: /usr/local/alfresco/tomcat/shared
          subPath: config/
        securityContext:
          runAsUser: 0
      containers:
      - name: {{ include "edusharing_repository_service.name" . }}-server
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-repository-service:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        {{- if .Values.config.jvm.debug }}
        args: [ "catalina.sh", "jpda", "run" ]
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_service.name" . }}-env
        - secretRef:
            name: {{ include "edusharing_repository_service.name" . }}-env
        ports:
        - name: api-internal
          containerPort: 8080
        - name: api-external
          containerPort: 8081
        - name: gossip
          containerPort: 5701
        - name: jmx
          containerPort: 7199
        {{- if .Values.config.jvm.debug }}
        - name: jpda
          containerPort: 5005
        {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metric
          containerPort: 9090
        {{- end }}
        volumeMounts:
        - name: share
          mountPath: /opt/alfresco/alf_data
          subPath: data/
        - name: share
          mountPath: /usr/local/tomcat/shared
          subPath: config/
        - name: file
          mountPath: /usr/local/tomcat/conf/redisson.yaml
          subPath: redisson.yaml
        {{- if .Values.config.saml.enabled }}
        {{- if .Values.config.saml.config }}
        - name: saml-file
          mountPath: /usr/local/tomcat/webapps/edu-sharing/WEB-INF/securityContext.xml
          subPath: securityContext.xml
        {{- end }}
        {{- if .Values.config.saml.files }}
        - name: saml-files
          mountPath: /usr/local/tomcat/webapps/edu-sharing/WEB-INF/classes/saml
        {{- end }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          tcpSocket:
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          httpGet:
            path: /edu-sharing/rest/_about/status/SERVICE?timeoutSeconds={{ add1 .timeoutSeconds }}
            httpHeaders:
            - name: Accept
              value: application/json
            - name: Content-Type
              value: application/json
            port: api-internal
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      - name: {{ include "edusharing_repository_service.name" . }}-transform
        image: {{ .Values.global.image.registry }}/{{ .Values.global.image.repository }}-repository-transform:{{ .Values.global.image.tag }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "edusharing_repository_service.name" . }}-env
        ports:
        - name: api
          containerPort: 8100
        {{- with .Values.transform.livenessProbe }}
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: 1
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.transform.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-ec"
            - |
              unoconv -n -c 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' --stdout -f html /etc/hostname >/dev/null
          failureThreshold: {{ .failureThreshold }}
          initialDelaySeconds: {{ .initialDelaySeconds }}
          periodSeconds: {{ .periodSeconds }}
          successThreshold: {{ .successThreshold }}
          timeoutSeconds: {{ .timeoutSeconds }}
        {{- end }}
        {{- with .Values.transform.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.transform.securityContext }}
        securityContext: {{ toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.global.image.pullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{ with .Values.terminationGracePeriod }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- if or .Values.nodeAffinity .Values.podAntiAffinity }}
      affinity:
        {{- with .Values.nodeAffinity }}
        nodeAffinity: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.podAntiAffinity }}
        podAntiAffinity:
          {{- if eq .Values.podAntiAffinity "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels: {{ include "edusharing_repository_service.labels.instance" . | nindent 16 }}
          {{- else if eq .Values.podAntiAffinity "soft" }}
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels: {{ include "edusharing_repository_service.labels.instance" . | nindent 18 }}
          {{- end }}
        {{- end }}
      {{- end }}
      volumes:
      - name: share
        persistentVolumeClaim:
          claimName: {{ include "edusharing_repository_service.pvc.share" . }}
      - name: file
        configMap:
          name: {{ include "edusharing_repository_service.name" . }}-file
      {{- if .Values.config.saml.enabled }}
      {{- if .Values.config.saml.config }}
      - name: saml-file
        configMap:
          name: {{ include "edusharing_repository_service.name" . }}-saml-file
      {{- end }}
      {{- if .Values.config.saml.files }}
      - name: saml-files
        configMap:
          name: {{ include "edusharing_repository_service.name" . }}-saml-files
      {{- end }}
      {{- end }}

